//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package timer
import (
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type TimerVgen struct {
	Time *int
}
func (v TimerVgen) Validate(rules TimerRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.Time.Validate("Time", v.Time))
	return errors
}
func (r TimerRules) Validate(prefix string, input TimerVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(r.Time.Validate(prefix+".Time", input.Time))
	return errors
}
type TimerRules struct {
	Time vgen.Rules[int]
}
func (v TimerVgen) Convert() Timer {
	var res Timer
	if v.Time != nil {
		res.Time = *v.Time
	}
	return res
}
func (v TimerVgen) ValidatedConvert(rules TimerRules) (Timer, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Timer{}, errors
	}
	return v.Convert(), errors
}
func (r TimerRules) Extend(rules TimerRules) TimerRules {
	r.Time.Rules = append(r.Time.Rules, rules.Time.Rules...)
	r.Time.Required = r.Time.Required || rules.Time.Required
	return r
}
