//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type Test1Vgen struct {
	field1 *string
}
func (v Test1Vgen) Validate(rules Test1Rules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.field1.Validate("field1", v.field1))
	return errors
}
func (rules Test1Rules) Validate(prefix string, input Test1Vgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.field1.Validate(prefix+".field1", input.field1))
	return errors
}
type Test1Rules struct {
	field1 vgen.Rules[string]
}
func (v Test1Vgen) Convert() Test1 {
	var res Test1
	if v.field1 != nil {
		res.field1 = *v.field1
	}
	return res
}
func (v Test1Vgen) ValidatedConvert(rules Test1Rules) (Test1, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Test1{}, errors
	}
	return v.Convert(), errors
}
type Test2Vgen struct {
	field1 *string
}
func (v Test2Vgen) Validate(rules Test2Rules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.field1.Validate("field1", v.field1))
	return errors
}
func (rules Test2Rules) Validate(prefix string, input Test2Vgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.field1.Validate(prefix+".field1", input.field1))
	return errors
}
type Test2Rules struct {
	field1 vgen.Rules[string]
}
func (v Test2Vgen) Convert() Test2 {
	var res Test2
	if v.field1 != nil {
		res.field1 = *v.field1
	}
	return res
}
func (v Test2Vgen) ValidatedConvert(rules Test2Rules) (Test2, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Test2{}, errors
	}
	return v.Convert(), errors
}
