//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	"github.com/stofffe/vgen"
)
type PointerVgen struct {
	Name *[]*string `json:"name"`
	Age *[]int
	Pet **string
}
func (v PointerVgen) Validate(rules PointerRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Name.Validate("Name", v.Name))
	errors.AddErrors(rules.Age.Validate("Age", v.Age))
	errors.AddErrors(rules.Pet.Validate("Pet", v.Pet))
	return errors
}
func (rules PointerRules) Validate(prefix string, input *PointerVgen) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Name.Validate(prefix+".Name", input.Name))
	errors.AddErrors(rules.Age.Validate(prefix+".Age", input.Age))
	errors.AddErrors(rules.Pet.Validate(prefix+".Pet", input.Pet))
	return errors
}
type PointerRules struct {
	Name vgen.Rules[[]*string]
	Age vgen.Rules[[]int]
	Pet vgen.Rules[*string]
}
