//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	"github.com/stofffe/vgen"
)
type PointerVgen struct {
	Name **string `json:"name"`
}
func (v PointerVgen) Validate(rules PointerRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Name.Validate("name", v.Name))
	return errors
}
func (rules PointerRules) Validate(prefix string, input *PointerVgen) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Name.Validate(prefix+".name", input.Name))
	return errors
}
type PointerRules struct {
	Name vgen.Rules[*string]
}
func (v PointerVgen) Convert() Pointer {
	var res Pointer
	if v.Name != nil {
		res.Name = *v.Name
	}
	return res
}
