//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type PersonVgen struct {
	name *string
	nickname *string
	age *int
}
func (v PersonVgen) Validate(rules PersonRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.name.Validate("name", v.name))
	errors.AddErrors(rules.nickname.Validate("nickname", v.nickname))
	errors.AddErrors(rules.age.Validate("age", v.age))
	return errors
}
func (r PersonRules) Validate(prefix string, input PersonVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(r.name.Validate(prefix+".name", input.name))
	errors.AddErrors(r.nickname.Validate(prefix+".nickname", input.nickname))
	errors.AddErrors(r.age.Validate(prefix+".age", input.age))
	return errors
}
type PersonRules struct {
	name vgen.Rules[string]
	nickname vgen.Rules[string]
	age vgen.Rules[int]
}
func (v PersonVgen) Convert() Person {
	var res Person
	if v.name != nil {
		res.name = *v.name
	}
	if v.nickname != nil {
		res.nickname = *v.nickname
	}
	if v.age != nil {
		res.age = *v.age
	}
	return res
}
func (v PersonVgen) ValidatedConvert(rules PersonRules) (Person, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Person{}, errors
	}
	return v.Convert(), errors
}
func (r PersonRules) Extend(rules PersonRules) PersonRules {
	r.name.Rules = append(r.name.Rules, rules.name.Rules...)
	r.name.Required = r.name.Required || rules.name.Required
	r.nickname.Rules = append(r.nickname.Rules, rules.nickname.Rules...)
	r.nickname.Required = r.nickname.Required || rules.nickname.Required
	r.age.Rules = append(r.age.Rules, rules.age.Rules...)
	r.age.Required = r.age.Required || rules.age.Required
	return r
}
