//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type TestVgen struct {
	bestResult *ResultVgen
	allResults *[]ResultVgen
}
func (v TestVgen) Validate(rules TestRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.bestResult.Validate("bestResult", v.bestResult))
	errors.AddErrors(rules.allResults.Validate("allResults", v.allResults))
	return errors
}
func (r TestRules) Validate(prefix string, input TestVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(r.bestResult.Validate(prefix+".bestResult", input.bestResult))
	errors.AddErrors(r.allResults.Validate(prefix+".allResults", input.allResults))
	return errors
}
type TestRules struct {
	bestResult vgen.Rules[ResultVgen]
	allResults vgen.Rules[[]ResultVgen]
}
func (v TestVgen) Convert() Test {
	var res Test
	if v.bestResult != nil {
		res.bestResult = v.bestResult.Convert()
	}
	if v.allResults != nil {
		elem := *v.allResults
		res.allResults = make([]Result, len(elem))
		for i0, elem := range elem {
			res.allResults[i0] = elem.Convert()
		}
	}
	return res
}
func (v TestVgen) ValidatedConvert(rules TestRules) (Test, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Test{}, errors
	}
	return v.Convert(), errors
}
func (r TestRules) Extend(rules TestRules) TestRules {
	r.bestResult.Rules = append(r.bestResult.Rules, rules.bestResult.Rules...)
	r.bestResult.Required = r.bestResult.Required || rules.bestResult.Required
	r.allResults.Rules = append(r.allResults.Rules, rules.allResults.Rules...)
	r.allResults.Required = r.allResults.Required || rules.allResults.Required
	return r
}
type ResultVgen struct {
	score *string
}
func (v ResultVgen) Validate(rules ResultRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.score.Validate("score", v.score))
	return errors
}
func (r ResultRules) Validate(prefix string, input ResultVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(r.score.Validate(prefix+".score", input.score))
	return errors
}
type ResultRules struct {
	score vgen.Rules[string]
}
func (v ResultVgen) Convert() Result {
	var res Result
	if v.score != nil {
		res.score = *v.score
	}
	return res
}
func (v ResultVgen) ValidatedConvert(rules ResultRules) (Result, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Result{}, errors
	}
	return v.Convert(), errors
}
func (r ResultRules) Extend(rules ResultRules) ResultRules {
	r.score.Rules = append(r.score.Rules, rules.score.Rules...)
	r.score.Required = r.score.Required || rules.score.Required
	return r
}
