//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	"github.com/stofffe/vgen"
)
type TestVgen struct {
	BestResult *ResultVgen
	AllResults *[]ResultVgen
}
func (v TestVgen) Validate(rules TestRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.BestResult.Validate("pet", v.BestResult))
	errors.AddErrors(rules.AllResults.Validate("pets", v.AllResults))
	return errors
}
func (rules TestRules) Validate(prefix string, input *TestVgen) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.BestResult.Validate(prefix+".pet", input.BestResult))
	errors.AddErrors(rules.AllResults.Validate(prefix+".pets", input.AllResults))
	return errors
}
type TestRules struct {
	BestResult vgen.Rules[ResultVgen]
	AllResults vgen.Rules[[]ResultVgen]
}
type ResultVgen struct {
	Score *string
}
func (v ResultVgen) Validate(rules ResultRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Score.Validate("name", v.Score))
	return errors
}
func (rules ResultRules) Validate(prefix string, input *ResultVgen) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Score.Validate(prefix+".name", input.Score))
	return errors
}
type ResultRules struct {
	Score vgen.Rules[string]
}
