//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type ArrayVgen struct {
	vector *[]int
	matrix *[][]int
}
func (v ArrayVgen) Validate(rules ArrayRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.vector.Validate("vector", v.vector))
	errors.AddErrors(rules.matrix.Validate("matrix", v.matrix))
	return errors
}
func (rules ArrayRules) Validate(prefix string, input ArrayVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.vector.Validate(prefix+".vector", input.vector))
	errors.AddErrors(rules.matrix.Validate(prefix+".matrix", input.matrix))
	return errors
}
type ArrayRules struct {
	vector vgen.Rules[[]int]
	matrix vgen.Rules[[][]int]
}
func (v ArrayVgen) Convert() Array {
	var res Array
	if v.vector != nil {
		res.vector = *v.vector
	}
	if v.matrix != nil {
		res.matrix = *v.matrix
	}
	return res
}
func (v ArrayVgen) ValidatedConvert(rules ArrayRules) (Array, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Array{}, errors
	}
	return v.Convert(), errors
}
