//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type PersonVgen struct {
	name *string
	auth *string
}
func (v PersonVgen) Validate(rules PersonRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.name.Validate("name", v.name))
	errors.AddErrors(rules.auth.Validate("auth", v.auth))
	return errors
}
func (r PersonRules) Validate(prefix string, input PersonVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(r.name.Validate(prefix+".name", input.name))
	errors.AddErrors(r.auth.Validate(prefix+".auth", input.auth))
	return errors
}
type PersonRules struct {
	name vgen.Rules[string]
	auth vgen.Rules[string]
}
func (v PersonVgen) Convert() Person {
	var res Person
	if v.name != nil {
		res.name = *v.name
	}
	if v.auth != nil {
		res.auth = *v.auth
	}
	return res
}
func (v PersonVgen) ValidatedConvert(rules PersonRules) (Person, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Person{}, errors
	}
	return v.Convert(), errors
}
func (r PersonRules) Extend(rules PersonRules) PersonRules {
	r.name.Rules = append(r.name.Rules, rules.name.Rules...)
	r.name.Required = r.name.Required || rules.name.Required
	r.auth.Rules = append(r.auth.Rules, rules.auth.Rules...)
	r.auth.Required = r.auth.Required || rules.auth.Required
	return r
}
