//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	"github.com/stofffe/vgen"
)
type VectorVgen struct {
	vector *[]float32
}
func (v VectorVgen) Validate(rules VectorRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.vector.Validate("vector", v.vector))
	return errors
}
func (rules VectorRules) Validate(prefix string, input VectorVgen) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.vector.Validate(prefix+".vector", input.vector))
	return errors
}
type VectorRules struct {
	vector vgen.Rules[[]float32]
}
