//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	"github.com/stofffe/vgen"
)
type CustomVgen struct {
	vector *[]float32
}
func (v CustomVgen) Validate(rules CustomRules) vgen.ErrorMap {
	errors := vgen.EmptyErrorMap()
	errors.AddErrors(rules.vector.Validate("vector", v.vector))
	return errors
}
func (rules CustomRules) Validate(prefix string, input CustomVgen) vgen.ErrorMap {
	errors := vgen.EmptyErrorMap()
	errors.AddErrors(rules.vector.Validate(prefix+".vector", input.vector))
	return errors
}
type CustomRules struct {
	vector vgen.Rules[[]float32]
}
func (v CustomVgen) Convert() Custom {
	var res Custom
	if v.vector != nil {
		res.vector = *v.vector
	}
	return res
}
func (v CustomVgen) ValidatedConvert(rules CustomRules) (Custom, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Custom{}, errors
	}
	return v.Convert(), errors
}
