//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	"github.com/stofffe/vgen"
)
type PersonVgen struct {
	Name *string `json:"name"`
	Age *int `json:"age"`
}
func (v PersonVgen) Validate(rules PersonRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Name.Validate("Name", v.Name))
	errors.AddErrors(rules.Age.Validate("Age", v.Age))
	return errors
}
func (rules PersonRules) Validate(prefix string, input PersonVgen) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.Name.Validate(prefix+".Name", input.Name))
	errors.AddErrors(rules.Age.Validate(prefix+".Age", input.Age))
	return errors
}
type PersonRules struct {
	Name vgen.Rules[string]
	Age vgen.Rules[int]
}
