//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type CharacterVgen struct {
	stats *map[string]int
}
func (v CharacterVgen) Validate(rules CharacterRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.stats.Validate("stats", v.stats))
	return errors
}
func (rules CharacterRules) Validate(prefix string, input CharacterVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.stats.Validate(prefix+".stats", input.stats))
	return errors
}
type CharacterRules struct {
	stats vgen.Rules[map[string]int]
}
func (v CharacterVgen) Convert() Character {
	var res Character
	if v.stats != nil {
		res.stats = *v.stats
	}
	return res
}
func (v CharacterVgen) ValidatedConvert(rules CharacterRules) (Character, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Character{}, errors
	}
	return v.Convert(), errors
}
