//
// CODE GENERATED BY VGEN
//
// DO NOT EDIT
//

package main

import "github.com/stofffe/vgen/vgen"

type PersonVgen struct {
	name      *string
	age       *int
	nicknames *[]string
	matrix    *[][]int
	stats     *map[string]int
}

func (p PersonVgen) Validate(rules PersonRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	// name
	errors.AddErrors(rules.name.Validate("name", p.name))
	// age
	errors.AddErrors(rules.age.Validate("age", p.age))
	// nicknames
	errors.AddErrors(rules.nicknames.Validate("nicknames", p.nicknames))
	// matrix
	errors.AddErrors(rules.matrix.Validate("matrix", p.matrix))
	// stats
	errors.AddErrors(rules.stats.Validate("matrix", p.stats))

	return errors
}

type PersonRules struct {
	name      vgen.Rules[string]
	age       vgen.Rules[int]
	nicknames vgen.Rules[[]string]
	matrix    vgen.Rules[[][]int]
	stats     vgen.Rules[map[string]int]
}
