//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	"github.com/stofffe/vgen"
)
type PersonVgen struct {
	name *string
	age *int
}
func (v PersonVgen) Validate(rules PersonRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.name.Validate("name", v.name))
	errors.AddErrors(rules.age.Validate("age", v.age))
	return errors
}
func (rules PersonRules) Validate(prefix string, input PersonVgen) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.name.Validate(prefix+".name", input.name))
	errors.AddErrors(rules.age.Validate(prefix+".age", input.age))
	return errors
}
type PersonRules struct {
	name vgen.Rules[string]
	age vgen.Rules[int]
}
