// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
package main

import (
	"github.com/stofffe/vgen/vgen"
)

type PersonVgen struct {
	name      *string
	age       *int
	nicknames *[]string
	matrix    *[][]int
	stats     *map[string]int
}

func (v PersonVgen) Validate(rules PersonRules) vgen.ErrorMap {
	errors := make(vgen.ErrorMap)
	errors.AddErrors(rules.name.Validate("name", v.name))
	errors.AddErrors(rules.age.Validate("age", v.age))
	errors.AddErrors(rules.nicknames.Validate("nicknames", v.nicknames))
	errors.AddErrors(rules.matrix.Validate("matrix", v.matrix))
	errors.AddErrors(rules.stats.Validate("stats", v.stats))
	return errors
}

type PersonRules struct {
	name      vgen.Rules[string]
	age       vgen.Rules[int]
	nicknames vgen.Rules[[]string]
	matrix    vgen.Rules[[][]int]
	stats     vgen.Rules[map[string]int]
}
