//
// THIS FILE IS GENERATED BY VGEN
// DO NOT EDIT
//
package main
import (
	timer "github.com/stofffe/vgen/examples/import/timer"
	vgen "github.com/stofffe/vgen/pkg/vgen"
)
type ImportVgen struct {
	clock *timer.Clock
	timer *timer.TimerVgen
}
func (v ImportVgen) Validate(rules ImportRules) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(rules.clock.Validate("clock", v.clock))
	errors.AddErrors(rules.timer.Validate("timer", v.timer))
	return errors
}
func (r ImportRules) Validate(prefix string, input ImportVgen) vgen.ErrorMap {
	var errors vgen.ErrorMap
	errors.AddErrors(r.clock.Validate(prefix+".clock", input.clock))
	errors.AddErrors(r.timer.Validate(prefix+".timer", input.timer))
	return errors
}
type ImportRules struct {
	clock vgen.Rules[timer.Clock]
	timer vgen.Rules[timer.TimerVgen]
}
func (v ImportVgen) Convert() Import {
	var res Import
	if v.clock != nil {
		res.clock = *v.clock
	}
	if v.timer != nil {
		res.timer = v.timer.Convert()
	}
	return res
}
func (v ImportVgen) ValidatedConvert(rules ImportRules) (Import, vgen.ErrorMap) {
	errors := v.Validate(rules)
	if errors != nil {
		return Import{}, errors
	}
	return v.Convert(), errors
}
func (r ImportRules) Extend(rules ImportRules) ImportRules {
	r.clock.Rules = append(r.clock.Rules, rules.clock.Rules...)
	r.clock.Required = r.clock.Required || rules.clock.Required
	r.timer.Rules = append(r.timer.Rules, rules.timer.Rules...)
	r.timer.Required = r.timer.Required || rules.timer.Required
	return r
}
